meta_product_name: "Le Bateau"
meta_title: "Le Bateau - learning happens in the same boat"
meta_description: "A learning management system geared towards facilitating online learning in Mauritius. It creates the link between students and teachers such that all learning materials and enquiries occur on the same platform."
meta_image: "cover.jpeg" # should exist in `app/assets/images/`
